sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t outfox99/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true outfox99/docker-react npm run test -- --coverage

after_success:
  - echo "test success"